#!/bin/sh
#
# Do not configure this file. Edit /etc/default/mongodb instead
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/mongod
NAME=mongod
DESC="Mongo Database Server"

MONGOD_PID_FILE="/var/run/mongod.pid"
MONGOD_DB_PATH="/data/db"
MONGOD_LOCK_FILE="$MONGOD_DB_PATH/mongod.lock"
MONGOD_STORAGE_ENGINE="mmapv1"
MONGOD_EXTRA_ARGS=""

set -e

test -r /etc/default/mongod && . /etc/default/mongod
test -x "$DAEMON" || exit 0

init_is_running() {
    [ -e $MONGOD_PID_FILE ] || return 1
    [ -d /proc/$(cat $MONGOD_PID_FILE) ] || return 1
    return 0
}

init_start() {
    [ -d $MONGOD_DB_PATH ] || mkdir -p $MONGOD_DB_PATH 

    echo -n "Starting $DESC: "
    start-stop-daemon -S \
        -x "$DAEMON" \
        -p $MONGOD_PID_FILE -- \
        --syslog \
        --fork \
        --quiet  \
        --dbpath $MONGOD_DB_PATH \
        --pidfilepath $MONGOD_PID_FILE \
        --storageEngine $MONGOD_STORAGE_ENGINE \
        $MONGOD_EXTRA_ARGS \
        2>&1 | logger
    echo "$NAME"
}

init_start_repair() {
    echo -n "Repairing database: "
    $DAEMON \
        --syslog \
        --quiet \
        --dbpath $MONGOD_DB_PATH \
        --storageEngine $MONGOD_STORAGE_ENGINE \
        --repair \
        2>&1 | logger

    if [ -s $MONGOD_LOCK_FILE ]; then
        echo "FAIL"
        echo -n "Wiping database path: "
        rm -rf $MONGOD_DB_PATH/*
        echo "OK"
    else
        echo "OK"
    fi
}

init_stop() {
    ignore_error=$1
    echo -n "Stopping $DESC: "
    start-stop-daemon -K \
        -x "$DAEMON" \
        -p $MONGOD_PID_FILE \
        -s 2 \
        2>&1 | logger && echo "OK"
    rm -f $MONGOD_PID_FILE
}

init_stop_wait() {
    echo -n "Waiting for daemon to exit: "
    for i in $(seq 10) "failed"; do
        [ -s $MONGOD_LOCK_FILE ] || break
        echo -n "."
        sleep 1
    done

    if [ $i == "failed" ]; then
        echo "FAIL"
    else
        echo "OK"
    fi
}

case "$1" in
    start)
        [ -s $MONGOD_LOCK_FILE ] && ! init_is_running && init_start_repair
        init_start
        ;;
    stop)
        [ -s $MONGOD_LOCK_FILE ] && init_stop
        ;;
    restart)
        init_is_running && init_stop && init_stop_wait
        [ -s $MONGOD_LOCK_FILE ] && init_start_repair
        init_start
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
